# Generated by Django 3.2.6 on 2021-08-23 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskdata',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
